from django.urls import path
from . import views  
urlpatterns = [
    path('new', views.new),
    path('home',views.home, name='home'),
    path('addteacher',views.addteacher, name='addteacher'),
    path('contact',views.contact,name='contact'),
    path('addcontact',views.addcontact,name='addcontact'),
    path('messages',views.messages,name="messages"),
    path('images', views.images, name='images'),
    path('img', views.img, name='img'),
    path('about', views.about, name='about'),
    path('achevments', views.achevments, name='achevments'),
    path('milestones', views.milestones, name='milestones'),
    path('activity', views.activity, name='activity'),
    path('socialwork', views.socialwork, name='socialwork'),
    path('msw', views.msw, name='msw'),
    path('bsw', views.bsw, name='bsw'),
    path('bswsyllabus', views.bswsyllabus, name='bswsyllabus'),
    path('mswsyllabus', views.mswsyllabus, name='mswsyllabus'),
    path('login', views.login, name='login'),
    path('alogout', views.alogout, name='alogout'),
    path('admission', views.admission, name='admission'),
    path('admson',views.admson,name='admson'),
    path('editing',views.editing,name='editing'),
    path('delevent',views.delevent, name='delevent'),
    path('details/<int:reqid>',views.details,name='details'),
    path('delete/<int:delid>',views.delete,name='delete'),
    path('ugdetails/<int:ugid>',views.ugdetails,name='ugdetails'),
    path('ugdel/<int:udid>',views.ugdel, name='ugdel'),
    path('success',views.success,name='success'),
    path('requests',views.requests,name='requests'),
    path('ugreq',views.ugreq, name='ugreq'),
    path('sdetails',views.sdetails,name='sdetails'),
    path('upadmission',views.upadmission,name='upadmission'),
    path('computerscience',views.computerscience,name='computerscience'),
    path('bsccs',views.bsccs,name='bsccs'),
    path('cssyllabus',views.cssyllabus,name='cssyllabus'),
    path('library',views.library,name='library'),
    path('hostel',views.hostel,name='hostel'),
    path('computerlab',views.computerlab,name='computerlab'),
    path('english',views.english,name='english'),
    path('baenglish',views.baenglish,name='baenglish'),
    path('maenglish',views.maenglish,name='maenglish'),
    path('admin',views.admin,name='admin'),
    path('psychology',views.psychology,name='psychology'),
    path('msc',views.msc,name='msc'),
    path('bsc',views.bsc,name='bsc'),
    path('bscsyllabus',views.bscsyllabus,name='bscsyllabus'),
    path('mscsyllabus',views.mscsyllabus,name='mscsyllabus'),
    path('title', views.title, name='title'),
    path('viewfile/<int:vid>',views.viewfile, name='viewfile'),
    path('plustwo/<int:plid>',views.plustwo, name='plustwo'),
    path('degree/<int:dgid>',views.degree, name='degree'),
    path('studlogin',views.studlogin, name='studlogin'),
    path('ugsslc/<int:sscid>',views.ugsslc, name='ugsslc'),
    path('ugplustwo/<int:upid>',views.ugplustwo, name='ugplustwo'),
    path('ugstudprofile', views.ugstudprofile, name='ugstudprofile'),
    path('ugsuccess',views.ugsuccess, name='ugsuccess'),
    path('updateug',views.updateug, name='updateug'),
    path('studentwelcome',views.studentwelcome, name='studentwelcome'),
    path('studlogout', views.studlogout, name='studlogout')


]


