from django.urls import path
from . import views  
urlpatterns = [
    path('new', views.new),
    path('home',views.home, name='home'),
    path('contact',views.contact,name='contact'),
    path('images', views.images, name='images'),
    path('about', views.about, name='about'),
    path('achevments', views.achevments, name='achevments'),
    path('milestones', views.milestones, name='milestones'),
    path('activity', views.activity, name='activity'),
    path('socialwork', views.socialwork, name='socialwork'),
    path('msw', views.msw, name='msw'),
    path('bsw', views.bsw, name='bsw'),
    path('bswsyllabus', views.bswsyllabus, name='bswsyllabus'),
    path('mswsyllabus', views.mswsyllabus, name='mswsyllabus'),
    path('login', views.login, name='login'),
    path('admission', views.admission, name='admission'),
    path('admson',views.admson,name='admson'),
    path('details',views.details,name='details'),
    path('success',views.success,name='success'),
    path('requests',views.requests,name='requests'),
    path('computerscience',views.computerscience,name='computerscience'),
    path('bsccs',views.bsccs,name='bsccs'),
    path('cssyllabus',views.cssyllabus,name='cssyllabus'),
    path('library',views.library,name='library'),
    path('hostel',views.hostel,name='hostel'),
    path('computerlab',views.computerlab,name='computerlab'),
    path('english',views.english,name='english'),
    path('baenglish',views.baenglish,name='baenglish'),
    path('maenglish',views.maenglish,name='maenglish'),
    path('admin',views.admin,name='admin'),
    path('psychology',views.psychology,name='psychology'),
    path('msc',views.msc,name='msc'),
    path('bsc',views.bsc,name='bsc'),
    path('bscsyllabus',views.bscsyllabus,name='bscsyllabus'),
    path('mscsyllabus',views.mscsyllabus,name='mscsyllabus'),
    path('title', views.title, name='title'),

]


