from django.urls import path
from django.conf.urls import url
from . import views  
urlpatterns = [
    path('new', views.new),
    path('home',views.home, name='home'),
    path('upcount',views.upcount, name='upcount'),
    path('displaycount',views.displaycount, name='displaycount'),
    path('contact',views.contact,name='contact'),
    path('editcontact',views.editcontact, name='editcontact'),
    path('showcontact',views.showcontact,name='showcontact'),
    path('messages',views.messages,name="messages"),
    path('images', views.images, name='images'),
    path('img', views.img, name='img'),
    path('about', views.about, name='about'),
    path('upmonth',views.upmonth, name='upmonth'),
    path('showmonth',views.showmonth,name='showmonth'),
    path('achevments', views.achevments, name='achevments'),
    path('milestones', views.milestones, name='milestones'),
    path('activity', views.activity, name='activity'),
    path('socialwork', views.socialwork, name='socialwork'),
    path('msw', views.msw, name='msw'),
    path('bsw', views.bsw, name='bsw'),
    path('bswsyllabus', views.bswsyllabus, name='bswsyllabus'),
    path('mswsyllabus', views.mswsyllabus, name='mswsyllabus'),
    path('login', views.login, name='login'),
    path('alogout', views.alogout, name='alogout'),
    path('admission', views.admission, name='admission'),
    path('admson',views.admson,name='admson'),
    path('editing',views.editing,name='editing'),
    path('delevent/<int:evtid>',views.delevent, name='delevent'),
    path('details/<int:reqid>',views.details,name='details'),
    path('delete/<int:delid>',views.delete,name='delete'),
    path('ugdetails/<int:ugid>',views.ugdetails,name='ugdetails'),
    path('ugdel/<int:udid>',views.ugdel, name='ugdel'),
    path('success',views.success,name='success'),
    path('requests',views.requests,name='requests'),
    path('ugreq',views.ugreq, name='ugreq'),
    path('sdetails',views.sdetails,name='sdetails'),
    path('upadmission',views.upadmission,name='upadmission'),
    path('computerscience',views.computerscience,name='computerscience'),
    path('bsccs',views.bsccs,name='bsccs'),
    path('cssyllabus',views.cssyllabus,name='cssyllabus'),
    path('library',views.library,name='library'),
    path('hostel',views.hostel,name='hostel'),
    path('computerlab',views.computerlab,name='computerlab'),
    path('english',views.english,name='english'),
    path('baenglish',views.baenglish,name='baenglish'),
    path('maenglish',views.maenglish,name='maenglish'),
    path('admin',views.admin,name='admin'),
    path('psychology',views.psychology,name='psychology'),
    path('msc',views.msc,name='msc'),
    path('bsc',views.bsc,name='bsc'),
    path('bscsyllabus',views.bscsyllabus,name='bscsyllabus'),
    path('mscsyllabus',views.mscsyllabus,name='mscsyllabus'),
    path('title', views.title, name='title'),
    path('viewfile/<int:vid>',views.viewfile, name='viewfile'),
    path('plustwo/<int:plid>',views.plustwo, name='plustwo'),
    path('degree/<int:dgid>',views.degree, name='degree'),
    path('studlogin',views.studlogin, name='studlogin'),
    path('ugsslc/<int:sscid>',views.ugsslc, name='ugsslc'),
    path('ugplustwo/<int:upid>',views.ugplustwo, name='ugplustwo'),
    path('ugstudprofile', views.ugstudprofile, name='ugstudprofile'),
    path('ugsuccess',views.ugsuccess, name='ugsuccess'),
    path('updateug',views.updateug, name='updateug'),
    path('studentwelcome',views.studentwelcome, name='studentwelcome'),
    path('studlogout', views.studlogout, name='studlogout'),
    path('addedimage',views.addedimage, name='addedimage'),
    path('delimage/<int:pcid>',views.delimage, name='delimage'),
    path('augmail/<int:amid>',views.augmail, name='augmail'),
    path('rugmail/<int:rmid>',views.rugmail, name='rugmail'),
    path('apgmail/<int:apid>',views.apgmail, name='apgmail'),
    path('rpgmail/<int:rpid>',views.rpgmail, name='rpgmail'),
    path('replymsg/<int:rplid>',views.replymsg, name='replymsg'),
    path('ugacademic',views.ugacademic, name='ugacademic'),
    path('pgacademic',views.pgacademic, name='pgacademic'),
    path('ugfees',views.ugfees, name='ugfees'),
    path('pgfees',views.pgfees, name='pgfees'),
    path('delugfees/<int:ufid>',views.delugfees, name='delugfees'),
    path('delpgfees/<int:pfid>',views.delpgfees, name='delpgfees'),
    path('editugfees/<int:eufid>', views.editugfees, name='editugfees'),
    path('editpgfees/<int:epfid>', views.editpgfees, name='editpgfees'),
]

    


