# Generated by Django 3.2.3 on 2021-09-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjaxUdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.BigIntegerField()),
                ('place', models.CharField(max_length=30)),
            ],
        ),
    ]
