# Generated by Django 3.2.3 on 2021-07-16 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second.login')),
            ],
        ),
    ]
