# Generated by Django 3.2.3 on 2021-07-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0002_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='parentname',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='phone',
            field=models.BigIntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='place',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
