# Generated by Django 3.2.3 on 2021-07-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0005_article_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('candidatename', models.CharField(max_length=50)),
                ('parentname', models.CharField(max_length=50)),
                ('phonenumber', models.BigIntegerField()),
                ('category', models.CharField(max_length=50)),
                ('application', models.CharField(max_length=100)),
                ('sslc', models.FileField(upload_to='certificates/')),
                ('plus2', models.FileField(upload_to='certificates/')),
                ('degree', models.FileField(upload_to='certificates/')),
                ('qualification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
