# Generated by Django 3.2.3 on 2021-08-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0006_admission_mylogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
