# Generated by Django 3.2.3 on 2021-08-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0008_content_studentlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='firstnum',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='secnum',
            field=models.BigIntegerField(null=True),
        ),
    ]
