# Generated by Django 3.2.3 on 2021-08-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0011_auto_20210831_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='usertype',
            field=models.CharField(default=10, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degree',
            name='usertype',
            field=models.CharField(default=10, max_length=20),
            preserve_default=False,
        ),
    ]
