# Generated by Django 3.2.3 on 2021-09-01 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0012_auto_20210831_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='password',
        ),
        migrations.RemoveField(
            model_name='studentlogin',
            name='studid',
        ),
        migrations.AddField(
            model_name='degree',
            name='logid',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='second.studentlogin'),
            preserve_default=False,
        ),
    ]
