# Generated by Django 3.2.3 on 2021-09-06 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0015_auto_20210902_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='month',
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second.mylogin')),
            ],
        ),
    ]
