# Generated by Django 3.2.3 on 2021-09-14 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0016_auto_20210906_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second.mylogin')),
            ],
        ),
    ]
