# Generated by Django 3.2.3 on 2021-09-15 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0017_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='reply',
            name='mesageid',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='second.message'),
            preserve_default=False,
        ),
    ]
