# Generated by Django 3.2.3 on 2021-09-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0018_auto_20210915_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='mesageid',
        ),
    ]
