# Generated by Django 3.2.3 on 2021-09-15 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0019_remove_reply_mesageid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='mesageid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='second.message'),
            preserve_default=False,
        ),
    ]
