# Generated by Django 3.2.3 on 2021-09-17 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0020_reply_mesageid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UgAcademics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(max_length=30)),
                ('fees', models.CharField(max_length=30)),
                ('eligibility', models.CharField(max_length=30)),
                ('job', models.TextField()),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second.mylogin')),
            ],
        ),
        migrations.CreateModel(
            name='PgAcademics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(max_length=30)),
                ('fees', models.CharField(max_length=30)),
                ('eligibility', models.CharField(max_length=30)),
                ('job', models.TextField()),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second.mylogin')),
            ],
        ),
    ]
